apiVersion: v1
kind: Pod
metadata:
  generateName: producermq-
  labels:
    type: producermq
spec:
  containers:
  - name: producer-container
    image: your-private-registry.azurecr.io/rabbitmq-k8s-producer
    env:
      - name: RABBIT_URL
        value: YOUR_RABBIT_SERVICE_URL
      - name: QUEUE
        value: "workqueue"
      - name: RABBIT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: rabbitsecret
            key: password
  imagePullSecrets:
  - name: acrsecret